### ISSUE TITLE
Allow Pulumi remote deploys

### ISSUE THREAD

**Issue by mvgijssel** [mvgijssel/setup#181]
After https://github.com/mvgijssel/setup/issues/179 it should now be safe to deploy Pulumi from the CI (and maybe ultimately from Pulumi Cloud deployments).

Things that are challenging when using a SSH tunnel

1. Tunnel is opened and closed before the actual update (https://github.com/pulumi/pulumi-kubernetes/issues/1857)
2. If the port number in the kubeconfig changes it will trigger a replacement of all kubernetes resources

This is talking about the exact issue: 
https://github.com/pulumi/pulumi/issues/9397

### TODO

- [x] Update command rule
- [ ] Test provisioner provision using docker target
- [ ] Setup Teleport on provisioner
- [ ] Setup Teleport machine ID for BuildBuddy
- [ ] Setup Bazel command to login to Teleport before executing Pulumi
- [ ] Setup Pulumi test rule in BuildBuddy and figure out if this can be rendered in GitHub
- [ ] Setup Pulumi deploy rule in BuildBuddy

**Comment by mvgijssel** [comment]
Instead of using SSH port forwarding use Teleport to manage access to all services (https://goteleport.com/).

**Comment by mvgijssel** [comment]
Split into separate issues.
