### ISSUE TITLE
Secret management

### ISSUE THREAD

**Issue by mvgijssel** [mvgijssel/setup#287]
Use 1Password connect with a dev and prod Vault. Setup the 1Password cli to generate the 1Password- redentials.json file and to issue tokens as described here https://github.com/1Password/connect.

Set the dev/prod credentials and tokens inside the BuildBuddy secrets as well (4 in total). 

Current secrets

- BuildBuddy teleport user + identity
- teleport-admin teleport user
- PagerDuty integration key
- Logz.io metrics id

### TODO

- [ ] Install Docker in provisioner 
- [ ] Install one password connect in provisioner 
- [ ] Setup Telegraf logz.ip output plugin with one password connect
- [ ] Setup open telemetry with one password connect
- [ ] Update bootstrap docs

**Comment by mvgijssel** [comment]
Updated bootstrap docs https://github.com/mvgijssel/setup/wiki/Bootstrap-provisioner.
