### ISSUE TITLE
Migrate Teleport to docker

### ISSUE THREAD

**Issue by mvgijssel** [mvgijssel/setup#297]
### TODO

- [ ] Backup existing data from Teleport
- [ ] Remove existing teleport installation
- [ ] Setup docker-compose file with Teleport
- [ ] Import backup data
- [ ] Make sure docker-compose file works with Renovatebot

**Comment by mvgijssel** [comment]
When running Teleport in docker the underlying node, provisioner, still needs to run some Teleport software to be able to SSH into the provisioner node. Therefore there's no real benefit / migrating teleport to docker just makes things more complicated.
