### ISSUE TITLE
Setup workstation testing

### ISSUE THREAD

**Issue by mvgijssel** [mvgijssel/setup#98]
Now that workstation provisioning is done with Pyinfra (https://github.com/mvgijssel/setup/pull/96) there need to be automated tests to verify that everything keeps working as expected. https://github.com/inspec/inspec looks like the most mature framework to use for infrastructure testing and is also already used for the hypervisor testing.

For similar reasons as outlined here https://github.com/mvgijssel/setup/issues/97 let's move these tests into a docker container so we're not dependent on host (macOS) dependencies when installing/compiling Ruby dependencies. 

## TODO tests

- [ ] expect `fig docter` to return exit status 0
- [ ] expect `python` binary to come from asdf (and not built-in macOS)
- [ ] ensure we are using git version > 2.34 for git commit signing https://developer.1password.com/docs/ssh/git-commit-signing
- [ ] ensure `/etc/ssh/sshd_config` contains a line only allowing docker-for-mac vm access to macOS
